### PR TITLE
SCT-58 Ignore temporary narratives re event generation

### PR DESCRIPTION
**Pull request by MrCreosote**
@briehl - should definitely review
@arfathpasha - may be interested

### CODE REVIEW

**Comment by MrCreosote** [comment]
Tested manually.

**Comment by MrCreosote** [comment]
Related PRs:
https://github.com/kbaseapps/NarrativeService/pull/43
https://github.com/kbase/narrative/pull/1227

**Comment by briehl** [comment]
This looks good, matches what we talked about.

**Comment by MrCreosote** [comment]
https://github.com/kbase/KBaseSearchEngine/pull/120

**Pull request merged**
