### PR TITLE
CE-151: Adding kb-sdk-generated classes for credit metadata

### PR DESCRIPTION
**Pull request by ialarmedalien**
Autogenerated classes for credit metadata, as generated by everyone's favourite compiler, kb-sdk.

### CODE REVIEW

**Review by MrCreosote — COMMENTED** [review]
can you just run `make compile` so the other language libs, and more importantly, the html docs get updated?

Otherwise I'm assuming the changes came straight from the compiler and therefore don't need review

**Comment by MrCreosote** [comment]
We may want to consider removing the generated code (except for the WorkspaceService) from the coverage calculations

**Comment by ialarmedalien** [comment]
I transferred these over from the branch with the workspace spec updates in it just so I could work on the ArgUtils and other pieces that need these objects. When that other branch gets merged to develop, I can do a PR with all the docs updates.

**Review by MrCreosote — APPROVED** [review]
Fair enough

**Pull request merged**
