### PR TITLE
Fix for sharing with KBase users not belonging to the KBase globus group

### PR DESCRIPTION
**Pull request by msneddon**
This PR hotfix simply updates the auth library dependency to 0.3.1, and creates new WS release 0.3.5.  Note: it also brings in some merge commits from master that had not yet been merged back down to dev.

It will not compile until this PR is accepted into jars:
https://github.com/kbase/jars/pull/16

See also changes in the auth library:
https://github.com/kbase/auth/pull/14

### CODE REVIEW

**Comment by msneddon** [comment]
@kkellerlbl @scanon - Can one of you please review this PR?  Gavin is the only other person right now with commit privileges, and he's currently out.  It's a very small change, and my local tests are all passing, but I want to get out of the habit of accepting my own PRs.  Thanks.

**Comment by kkellerlbl** [comment]
Mike and I agreed we should wait and see what happens with the PR on auth (https://github.com/kbase/jars/pull/16) before merging this one.

**Comment by msneddon** [comment]
The PR to the auth library was updated to go against the develop branch:
https://github.com/kbase/auth/pull/15

**Comment by msneddon** [comment]
The auth libraries have been updated, so this updated dependency is ready to accept now too.
See KBASE-2024

**Pull request merged**
