### PR TITLE
Update to fixed auth client, add creds for checking users, more

### PR DESCRIPTION
**Pull request by MrCreosote**
- updated auth client. This fixes failures when trying to share a workspace with more than 1 user.
  - Note only updated to the configurable client where necessary. Many places in the code still use the static client.
- added config for creds for user to use when querying user data on Globus. Needs to be a kbase_users manager so that all users are visible regardless of their Globus user profile settings.
- Did some refactoring to remove duplicate code

### CODE REVIEW

**Comment by msneddon** [comment]
All relevant tests pass so I'll accept this into dev-candidate, but running the tests uncovered an unrelated issue caused by a Shock update.

All tests pass on an old commit of Shock (Aug 8 - fc6d2b2e82446), but on the most recent version of Shock (1e7da409e655a4), a HandleTest in the Workspace fails with this error:

    [junit] Testcase: basicHandleTest took 2.286 sec
    [junit] 	FAILED
    [junit] correct shock acls
    [junit] Expected: is <[us.kbase.shock.client.ShockUserId [id=be558931-0432-4846-a73b-eba05f4c7b42], us.kbase.shock.client.ShockUserId [id=c45b4c31-c7f0-4f6a-9ad5-0d07281370d5]]>
    [junit]      got: <[us.kbase.shock.client.ShockUserId [id=be558931-0432-4846-a73b-eba05f4c7b42]]>
    [junit] 
    [junit] junit.framework.AssertionFailedError: correct shock acls
    [junit] Expected: is <[us.kbase.shock.client.ShockUserId [id=be558931-0432-4846-a73b-eba05f4c7b42], us.kbase.shock.client.ShockUserId [id=c45b4c31-c7f0-4f6a-9ad5-0d07281370d5]]>
    [junit]      got: <[us.kbase.shock.client.ShockUserId [id=be558931-0432-4846-a73b-eba05f4c7b42]]>
    [junit] 
    [junit] 	at us.kbase.workspace.test.kbase.HandleTest.checkReadAcl(HandleTest.java:384)
    [junit] 	at us.kbase.workspace.test.kbase.HandleTest.basicHandleTest(HandleTest.java:331)
    [junit] 

Digging deeper, the error in Shock is:
[EROR] Only the node owner can edit/view node ACL's

All the HandleManager admin and shock admin configs are setup properly, so there is a new error is setting permissions of shock nodes.

**Comment by MrCreosote** [comment]
It appears that Shock is not recognizing the admin user name from the config file in the later commit.

**Comment by jaredbischof** [comment]
The error message could be changed but looking at the code, for the commit referenced above, Shock is checking if the user is flagged as an admin.

	if n.Acl.Owner != u.Uuid && n.Acl.Owner != "" && !u.Admin {
		err_msg := "Only the node owner can edit/view node ACL's"
		logger.Error(err_msg)
		responder.RespondWithError(ctx, http.StatusUnauthorized, err_msg)
		return
	}

Shock must be restarted for the admin list to be read, was this done?

**Comment by jaredbischof** [comment]
I will checkout that commit and test it.

**Comment by MrCreosote** [comment]
@jaredbischof 

> Shock must be restarted for the admin list to be read, was this done?

You mean you have to start it twice with the same config...?

What happens is that the test writes out a config file with the admin set, and then starts shock using that config file. Is there something beyond that that needs to happen?

**Comment by jaredbischof** [comment]
No, I just meant that Shock only reads the config file at start time.  What you are doing sounds like it should be working.  Could you send me your config file?  I checked out that code and it appears to work for me so I haven't figured out the problem yet.

**Comment by MrCreosote** [comment]
```
[Address]
# IP and port for api
# Note: use of port 80 may require root access
# 0.0.0.0 will bind Shock to all IP's
api-ip=0.0.0.0
api-port=53952

[Admin]
email=shock-admin@kbase.us
users=kbasetest8

[Anonymous]
# Controls an anonymous user's ability to read/write
# values: true/false
read=false
write=false
create-user=false

[Auth]
globus_token_url=https://nexus.api.globusonline.org/goauth/token?grant_type=client_credentials
globus_profile_url=https://nexus.api.globusonline.org/users

[External]
api-url=http://localhost:53952

[Log]
perf_log=false

[Mongodb]
# Mongodb configuration
# Hostnames and ports hosts=host1[,host2:port,...,hostN]
hosts=localhost:38572
database=JSONRPCLayerHandleTest_ShockDB
user=foo
password=foo

[Mongodb-Node-Indices]
# See http://www.mongodb.org/display/DOCS/Indexes#Indexes-CreationOptions for more info on mongodb index options.
# key=unique:true/false[,dropDups:true/false][,sparse:true/false]
id=unique:true

[Paths]
# See documentation for details of deploying Shock
site=/home/crusherofheads/localgit/workspace_deluxe/workspacehandletemp/ShockController-1602782227657575109/shock/site
data=/home/crusherofheads/localgit/workspace_deluxe/workspacehandletemp/ShockController-1602782227657575109/shock/data
logs=/home/crusherofheads/localgit/workspace_deluxe/workspacehandletemp/ShockController-1602782227657575109/shock/logs
local_paths=
pidfile=

[Runtime]
GOMAXPROCS=
```

**Comment by jaredbischof** [comment]
Can you tell me what rest call is happening here?

**Comment by MrCreosote** [comment]
Must be https://github.com/kbase/handle_mngr/blob/ff26a5dc1213e77ad870d010eb8a2ef26641a91f/lib/Bio/KBase/HandleMngr/HandleMngrImpl.pm#L273

**Comment by jaredbischof** [comment]
Can you guys try testing this out with curl manually?  Sorry, but so far everything works for me (not claiming you're wrong, just can't find the problem).  I recompiled the code using the commit referenced above, took the config you sent, changed just the paths, the mongo info, and the user name and it worked for me.

with users=jbischof in config file:

$ curl "http://localhost:53952/node/735cda0a-c054-43e1-973c-d6f676e83e64"                      
{"status":401,"data":null,"error":["No Authorization"]}

$ curl -H $AUTH -X GET "http://localhost:53952/node/735cda0a-c054-43e1-973c-d6f676e83e64/acl/read"
{"status":200,"data":{"read":["d24ff7e6-a094-4d12-9572-a3fe4d55976c"]},"error":null}

$ curl -H $AUTH -X PUT "http://localhost:53952/node/735cda0a-c054-43e1-973c-d6f676e83e64/acl/read?users=jbischof" 
{"status":200,"data":{"read":["d24ff7e6-a094-4d12-9572-a3fe4d55976c","228ffe8e-82f2-4375-8d78-841e715dbe8a"]},"error":null}

with users= in config file:

curl -H $AUTH -X GET "http://localhost:53952/node/735cda0a-c054-43e1-973c-d6f676e83e64/acl/read"
{"status":400,"data":null,"error":["Only the node owner can edit/view node ACL's"]

**Comment by MrCreosote** [comment]
Wait a sec - wasn't there a bug where if you started shock with an empty database it wouldn't register the admin user for some reason? I seem to remember something like that. The tests start with an empty mongo DB so that might be it. IIRC if you created a user and *then* restarted shock with an admin in the config it'd work.

**Comment by jaredbischof** [comment]
Yes, you're right.  Glad you remembered that, thanks.  This was driving me crazy.  That has been fixed but is coupled with the update to the ACL's which has not been updated in KBase production Shock yet.  I will ask Dan and Shane about moving forward with the update Monday.  Thanks.

**Comment by MrCreosote** [comment]
Ok, so the behavior we're seeing with the newer commit is expected, and you're planning on updating the KBase shock wrapper repo with the changes above before the next deploy - is that correct?

**Comment by jaredbischof** [comment]
This behavior was never intended.  It is in fact a bug.  I'm not sure how or why the bug was introduced but it has since been fixed in the Shock master branch.  The shock_service repo just isn't pointing to the newest code for Shock, which it shouldn't because we haven't upgraded KBase production Shock yet.  We can either a) update the submodule to point to the newest Shock and update KBase production Shock at the same time or b) I can put in a fix just for this if we're still not ready to upgrade Shock.  But, I'm hoping there's no reason to further delay the upgrade.

**Comment by MrCreosote** [comment]
I just meant that we know that the bug exists in the current head of the master branch of kbase/shock_service so the behavior we're seeing is expected, not that it's desired or intended behavior.

**Comment by jaredbischof** [comment]
Ah yes, correct.  Also, I spoke with Dan today and we're going to figure out a time to update production Shock in KBase.

**Comment by jaredbischof** [comment]
The submodule in the shock_service repo was updated this Monday just before the KBase production Shock server was updated.  Using this version of Shock should fix the problems you were experiencing.  Can you let me know if it did or did not?

**Pull request merged**
