### PR TITLE
Dockerized updates

### PR DESCRIPTION
**Pull request by sychan**
Modifications to the image to use the "dockerize" entrypoint.

### CODE REVIEW

**Comment by MrCreosote** [comment]
First quick comments:
* Could you please make this against dev-candidate: https://ci.kbase.us/services/ws/docs/developers.html
* Pretty sure there are lots of obsolete files that can now be deleted
* Update release notes

**Comment by sychan** [comment]
@MrCreosote I've rebased the PR against dev_candidate as requested, removed 2 files that were associated with the old entrypoint wrapper, and updated the release notes. There were no lingering database files because those were already moved out of this repo in the previous round of PR feedback.

**Comment by MrCreosote** [comment]
There's something really messed up here - there are commits in the PR dating back as far as mid september, which are already in the dev-candidate branch.

**Comment by MrCreosote** [comment]
Actually, they're not - looks like I synced develop -> dev-c locally but not in git. Fixing that now.

**Comment by sychan** [comment]
Yes, the PR looks much more reasonable now. Mergez-vous?

**Comment by MrCreosote** [comment]
I'm still seeing a zillion commits and tons of already reviewed code.

**Pull request closed without merging**
