### PR TITLE
Add a docker build to validate the dockerfile

### PR DESCRIPTION
**Pull request by sychan**
Add a docker build back into the travis.yml to validate the dockerfile.

### CODE REVIEW

**Comment by MrCreosote** [comment]
Once the build is updated to test multiple versions of mongoDB, this'll build a docker image every time. Can you set it up so it only builds the image once, regardless of the ENV matrix?

**Comment by MrCreosote** [comment]
@sychan you might want to pull develop into this branch as there are changes to travis.yml.

**Comment by ialarmedalien** [comment]
@MrCreosote I'm going to take a wild guess and say that this PR is probably not going to get finished. Close?

**Comment by MrCreosote** [comment]
It's just adding a docker build that doesn't get pushed to travis, and we're building and pushing images with GHA now, so yeah, I think it can be closed

**Pull request closed without merging**
