### PR TITLE
Remove Shock as a workspace backend

### PR DESCRIPTION
**Pull request by MrCreosote**
Shock is still used to test the handle and bytestream annotation
integrations. Swapping that for the Blobstore is another, much more
annoying, PR.

### CODE REVIEW

**Comment by MrCreosote** [comment]
image
It's... so beautiful

**Comment by MrCreosote** [comment]
Image build is expected to fail

**Review by sychan — APPROVED** [review]
It looks sensible enough, let's see if it breaks anything!

**Comment by sychan** [comment]
ps.
    You could have merged it into a branch in this repo and merged from there to see if the tokens work.

**Comment by MrCreosote** [comment]
I'm not really worried about the tokens, they're just for building the image, which isn't needed pre-merge.

**Pull request merged**
