### PR TITLE
Release 0.11.3 + minor bugfix

### PR DESCRIPTION
**Pull request by MrCreosote**
Draft until we've got enough data to conclude the S3 hang issue is fixed

### CODE REVIEW

**Comment by MrCreosote** [comment]
I assume the test image build failed as I don't have the correct creds

**Comment by MrCreosote** [comment]
and on the 2nd commit it passed. Interesting.

**Comment by jsfillman** [comment]
Taking it out of draft real quick to trigger a test image deploy.

**Review by jsfillman — APPROVED** [review]

**Comment by MrCreosote** [comment]
Approved by @kkellerlbl OOB

**Pull request merged**
