### PR TITLE
Remove JNA

### PR DESCRIPTION
**Pull request by MrCreosote**
JNA doesn't work in a shadow jar, which we'll need for workspace test rigs in other repos

### CODE REVIEW

**Review by ialarmedalien — APPROVED** [review]

**Comment by Xiangs18** [comment]
I am not that familiar with syslog4j. Is it similar to Log4j?

**Comment by MrCreosote** [comment]
No, it's used for sending log information to the linux syslog daemon as opposed to being a logging framework like log4j or slf4j

**Comment by Xiangs18** [comment]
Could you pleas explain more? Still try to understand why a simple logging framework like log4j is not in favor here.

**Comment by MrCreosote** [comment]
The system has a logging framework - it uses slf4j. slf4j does not provide code for logging to the syslog daemon. Syslog4j does, and so it was used as that was the requirement at the time

**Review by Xiangs18 — APPROVED** [review]
LGTM!

**Pull request merged**
